---
parameters: []
provision:
  os: "rhel"
  stage: "base"
  provider: "aws"
actions:
  - type: "host_script"
    title: "bring source code up to date"
    script: |-
      for repo in origin origin-web-console openshift-ansible; do
        oct sync remote "${repo}"
      done
  - type: "script"
    title: "build an origin release"
    repository: "origin"
    script: |-
      hack/build-base-images.sh
      OS_BUILD_ENV_PRESERVE=_output/local hack/env OS_ONLY_BUILD_PLATFORMS='linux/amd64' hack/build-rpm-release.sh
      sudo systemctl restart docker
      hack/build-images.sh
      sed -i 's|go/src|data/src|' _output/local/releases/rpms/origin-local-release.repo
      sudo cp _output/local/releases/rpms/origin-local-release.repo /etc/yum.repos.d/
  - type: "script"
    title: "build an openshift-ansible release"
    repository: "openshift-ansible"
    script: |-
      tito_tmp_dir="tito"
      mkdir -p "${tito_tmp_dir}"
      tito tag --offline --accept-auto-changelog
      tito build --output="${tito_tmp_dir}" --rpm --test --offline --quiet
      createrepo "${tito_tmp_dir}/noarch"
      cat << EOR > ./openshift-ansible-local-release.repo
      [openshift-ansible-local-release]
      baseurl = file://$( pwd )/${tito_tmp_dir}/noarch
      gpgcheck = 0
      name = OpenShift Ansible Release from Local Source
      EOR
      sudo cp ./openshift-ansible-local-release.repo /etc/yum.repos.d
  - type: "host_script"
    title: "package the AMI"
    script: |-
      oct package ami --upgrade
  - type: "script"
    title: "use a ramdisk for etcd"
    script: |-
      sudo su root <<SUDO
      mkdir -p /tmp
      mount -t tmpfs -o size=2048m tmpfs /tmp
      mkdir -p /tmp/etcd
      chmod a+rwx /tmp/etcd
      restorecon -R /tmp
      echo "ETCD_DATA_DIR=/tmp/etcd" >> /etc/environment
      SUDO
  - type: "host_script"
    title: "release the AMI"
    script: |-
      oct package ami --mark-ready
artifacts:
  - "/data/src/github/openshift/origin/_output/scripts"
generated_artifacts:
  installed_packages.log: 'sudo yum list installed'
system_journals:
  - docker.service